
name: sscma_micro                                   # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: develop                                    # <必选项> 组件版本号
description: 用于与AI平台进行交互的第三方模块           # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk
tag: 第三方模块                                       # <可选项> 组件分类，缺省值： ''

build_config:
  include:
    - SSCMA-Micro/core/*.hpp
    - SSCMA-Micro/sscma/*.hpp
    - SSCMA-Micro/porting/sophgo/cv181x/*.h
    - SSCMA-Micro/porting/sophgo/cv181x/*.hpp
  cflag: ''
  cxxflag: ''
  internal_include: 
    - SSCMA-Micro
    - SSCMA-Micro/porting/sophgo/cv181x
  define: 
    CONFIG_EL_TARGET_SOPHGO: 1
    CONFIG_EL_BOARD_CV181X: 1

source_file:
  - SSCMA-Micro/core/*.c
  - SSCMA-Micro/core/*.cpp
  - SSCMA-Micro/porting/sophgo/cv181x/*.c
  - SSCMA-Micro/porting/sophgo/cv181x/*.cpp